cookie:
  expiry_days: 30
  key: cookie_signature_key # Must be string
  name: cookie_name
credentials:
  usernames:
    coderacheal:
      email: coderacheal@gmail.com
      logged_in: False # Will be managed automatically
      name: Racheal Appiah-kubi
      password: abc # Will be hashed automatically
preauthorized:
  emails:
  - racheal.appiahkubi@azubiafrica.org